export const GET_ALL_GROUP = 'GET_ALL_GROUP';
export const ADD_GROUP = 'ADD_GROUP';
export const DELETE_GROUP = 'DELETE_GROUP';
export const UPDATE_GROUP = 'UPDATE_GROUP';

export const GET_ALL_GROUPS_SUCCESS = 'GET_ALL_GROUPS_SUCCESS';
export const ADD_GROUP_SUCCESS = 'ADD_GROUP_SUCCESS';
export const DELETE_GROUP_SUCCESS = 'DELETE_GROUP_SUCCESS';
export const UPDATE_GROUP_SUCCESS = 'UPDATE_GROUP_SUCCESS';

export const REQUEST_FAILURE = 'REQUEST_FAILURE';
export const CLEAR_GROUPS = 'CLEAR_GROUPS';
